cargo-features = ["edition"]

[package]
name = "aptf"
version = "0.1.0"
authors = ["iovxw <iovxw@outlook.com>"]
edition = '2018'

[dependencies]
indicatif = "0.9"
curl = "0.4"
tokio-curl = "0.1"
futures-preview = "0.3.0-alpha.3"